### ISSUE TITLE
variable `Bgra8` is not bound in all patterns

### ISSUE THREAD

**Issue by ea-dungn** [anhtumai/image2pdf#1]
Hi, just stumbled on this repo while I work on another project. Just want to let you know that currently the binary cannot be compiled because
```
error[E0408]: variable `Bgra8` is not bound in all patterns
  --> /home/dunix/.cargo/registry/src/github.com-1ecc6299db9ec823/image2pdf-0.1.0/src/image/alpha_remover.rs:49:13
   |
49 |             Rgba8 | Bgra8 => {
   |             ^^^^^   ----- variable not in all patterns
   |             |
   |             pattern doesn't bind `Bgra8`
   |
help: if you meant to match on a variant or a `const` item, consider making the path in the pattern qualified: `?::Bgra8`
  --> /home/dunix/.cargo/registry/src/github.com-1ecc6299db9ec823/image2pdf-0.1.0/src/image/alpha_remover.rs:49:21
   |
49 |             Rgba8 | Bgra8 => {
   |                     ^^^^^

For more information about this error, try `rustc --explain E0408`.
```

**Comment by anhtumai** [comment]
Ok I will have a look

**Comment by anhtumai** [comment]
@ea-dungn  what is the version of your `cargo` and `rustc` version? What is your operating system?

I built successfully with cargo and rustc 1.63.0

**Comment by ea-dungn** [comment]
Thanks for having a look on this. I'm on Windows' WSL2, `cargo` and `rustc` version 1.63.0.

**Comment by anhtumai** [comment]
I built successfully on both Linux (Fedora) and MacOs, so I think the error has something to do with WSL2.

**Comment by haydonryan** [comment]
When I run `cargo install image2pdf` I get the same error as above.

Running Arch (kernel 6.1.12-arch1-1) with cargo and rustc 1.69.0-nightly I got the exact same error.

Edit: retried with cargo 1.67.1 (8ecd4f20a 2023-01-10) same error.

cloning this repo and doing cargo build succeeds!
